### PR TITLE
Fix link to documentable assets tarball in README

### PR DESCRIPTION
**Pull request by paultcochrane**
This should make it easier for readers of the README to select the
correct file to download should they need to do so.

### CODE REVIEW

**Comment by paultcochrane** [comment]
You're right, the test error is directly from the issue I mention in #120.

**Comment by paultcochrane** [comment]
Unfortunately, there is only the one assets file and it's linked to version 1.0.1.  It might be a good idea to create such a file automatically as part of version build creation.  Also, I noticed that there are several releases that haven't been tagged and hence GitHub hasn't worked out that they are releases.  Dumb question: is it possible to do PRs with just simple tags?

**Comment by JJ** [comment]
I think that in that case, it was simply uploaded to the release. I was
wondering if it changed since then.

**Comment by paultcochrane** [comment]
Do you know how the assets file is generated?  I can't spot anything from the docs or the code.  Is it generated from the source in this repository?  Or from somewhere else?

**Comment by antoniogamiz** [comment]
I upload a tar file by hand. I plan to do this automatically but it's not implemented yet. The changes on this PR are already done in the development branch, so don't merge it. I will release a new version today.

**Comment by paultcochrane** [comment]
> The changes on this PR are already done in the development branch, so don't merge it.

Oh!  Should PRs be based on the development branch rather than master?

**Comment by antoniogamiz** [comment]
> Unfortunately, there is only the one assets file and it's linked to version 1.0.1. It might be a good idea to create such a file automatically as part of version build creation. Also, I noticed that there are several releases that haven't been tagged and hence GitHub hasn't worked out that they are releases. Dumb question: is it possible to do PRs with just simple tags?

Thanks for the feedback! I have in my plans to do that but it's not yet implemented. I will try to make the releases automatically (using Github Actions) and upload the `documentable-assets.tar.gz` to each release. 

I still have to document the template (#18) and the other files in the tar archive. 

Sorry for the broken and untag versions, that was entirely my fault for not keeping well enough releasing practices.

**Comment by antoniogamiz** [comment]
> > The changes on this PR are already done in the development branch, so don't merge it.
> 
> Oh! Should PRs be based on the development branch rather than master?

Yep, the idea is to have always a working version of Documentable in `master` (though right now that has not been the case).

**Comment by paultcochrane** [comment]
> Sorry for the broken and untag versions, that was entirely my fault for not keeping well enough releasing practices.

Hey, no problems!  I just happened to spot the issues and thought I'd point them out and make patches if I could.  i'm just trying to help out, so if there's any way I can support you better in further development, just let me know :-)

**Pull request merged**
