### PR TITLE
Change uses of Doc::TypeGraph to the new name as well

### PR DESCRIPTION
**Pull request by patrickbkr**

### CODE REVIEW

**Comment by Altai-man** [comment]
I think it wants to be merged into master, no?

**Comment by Altai-man** [comment]
Aaah, I see your intent! Sorry.

**Comment by Altai-man** [comment]
Superseded by https://github.com/Raku/Documentable/pull/159

**Comment by patrickbkr** [comment]
@Altai-man So this PR can be closed?

**Comment by Altai-man** [comment]
I believe so, yes.

**Pull request closed without merging**
